export const SET_SEARCH_TYPE = 'SET_SEARCH_TYPE';
export const TOGGLE_ALPHABET_SORT = 'TOGGLE_ALPHABET_SORT';
export const TOGGLE_SELECTED_CONTEXT = 'TOGGLE_SELECTED_CONTEXT';
export const TOGGLE_SELECTED_DIMENSION = 'TOGGLE_SELECTED_DIMENSION';
export const TOGGLE_SELECTED_VALUE = 'TOGGLE_SELECTED_VALUE';
export const SET_SELECTED_ALL_VALUES = 'SET_SELECTED_ALL_VALUES';
