export const TOGGLE_ALPHABET_SORT = 'TOGGLE_ALPHABET_SORT';
export const TOGGLE_SELECTED_FILTER = 'TOGGLE_SELECTED_FILTER';
export const SET_SELECTED_ALL_VALUES = 'SET_SELECTED_ALL_VALUES';
export const SET_MATCH_VALUES = 'SET_MATCH_VALUES';
export const SET_SEARCH_STRING = 'SET_SEARCH_STRING';
export const SET_SEARCH_TYPE = 'SET_SEARCH_TYPE';
